// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCuTAoViBgZg5puZnu1YiL9lhLIq9gVYo',
    appId: '1:820701014430:android:103e94e76f3e5043904e8f',
    messagingSenderId: '820701014430',
    projectId: 'event-app-ebra',
    storageBucket: 'event-app-ebra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQoCxC-eII-PfzB8mkMlU1DKL1877LsNU',
    appId: '1:820701014430:ios:a5710056819f9f5b904e8f',
    messagingSenderId: '820701014430',
    projectId: 'event-app-ebra',
    storageBucket: 'event-app-ebra.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMMx1iAc9_AHNCJ3oa6cv3yMIgUxOfi3g',
    appId: '1:820701014430:web:15870a9902d24e4e904e8f',
    messagingSenderId: '820701014430',
    projectId: 'event-app-ebra',
    authDomain: 'event-app-ebra.firebaseapp.com',
    storageBucket: 'event-app-ebra.firebasestorage.app',
    measurementId: 'G-SD2LGX4X2R',
  );
}
